description: >
  genymotion-saas orb needs Android so we will use CircleCI's Android convenience image:
  https://hub.docker.com/r/circleci/android

parameters:
  tag:
    default: api-29
    description: >
      Pick a specific circleci/android image tag:
      https://hub.docker.com/r/circleci/android/tags
    type: string

docker:
  - image: 'circleci/android:<<parameters.tag>>'
