description: >
  Android SDK tools are required for this orb, so we will use Circle CI image for Android:
  https://hub.docker.com/r/cimg/android/tags

parameters:
  tag:
    default: 2024.11.1
    description: >
      Pick a specific android image tag:
      https://hub.docker.com/r/cimg/android/tags
    type: string

docker:
  - image: 'cimg/android:<<parameters.tag>>'
